name: Random Bits
description: Blogging about college, open-source and randomness.
meta_description: ""

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://droftware.github.io'
google_analytics: 'UA-XXXXXXXX-X'
comments: true
future: true

# Details for the RSS feed generator
url:            'http://droftware.github.io'
author:         'Akshat Tandon'
